### ISSUE TITLE
will this work with periodic notes plugin

### ISSUE THREAD

**Issue by pcause** [reorx/obsidian-daily-notes-new-tab#2]
does this work with periodic notes?  if so, could you add to the README.md

**Comment by reorx** [comment]
Yes, if daily notes in the Periodic Notes plugin is enabled, it will use settings from Periodic Notes, otherwise, it will use settings from the Daily Notes Core Plugin. Will added to README later.

Currently, only daily notes is supported, it's possible to add support for other periodic note types like weekly or monthly, depending on users' need.

**Comment by reorx** [comment]
README has been updated, and the topic of periodic notes will be continued in #3
