### ISSUE TITLE
Unable to create a new file.

### ISSUE THREAD

**Issue by charleshan** [reorx/obsidian-daily-notes-new-tab#4]
I get an error message, "Unable to create a new file." when I use the shortcut to open today's daily note.

I see this in the console:
```
main.js:306 Failed to create file: '2. Areas/Daily Notes/2022-03-20.md' Error: File already exists.
```

**Comment by reorx** [comment]
This may be caused by the inconsistency of getting daily note file path between this plugin and obsidian-daily-notes-interface, I can reproduce by adding a trailing slash `/` at the end of the new file location, what's your?
<img width="725" alt="image" src="https://user-images.githubusercontent.com/405972/159290178-95d23ea7-7207-4b56-a4da-eed00b44d4d7.png">

**Comment by reorx** [comment]
[1.2.1](https://github.com/reorx/obsidian-daily-notes-new-tab/releases/tag/1.2.1) should fix this, please update and try again, you don't need to change anything in settings.
